export const TYPES = {
    SIGN_UP_INIT: 'SIGN_UP_INIT',
    SIGN_UP_SUCCEED: 'SIGN_UP_SUCCEED',
    SIGN_UP_FAILED: 'SIGN_UP_FAILED',
    LOG_IN_INIT: 'LOG_IN_INIT',
    LOG_IN_SUCCEED: 'LOG_IN_SUCCEED',
    LOG_IN_FAILED: 'LOG_IN_FAILED',
    CLEAN_UP_USER_DATA: 'CLEAN_UP_USER_DATA',
};
