export interface Product {
    name: string,
    id: string,
    photo: string,
    price: string,
    description: string,
    useForDescription: string,
    brand: string,
    model: string,
    yearOfIssue: number,
    housingMaterial: string,
    strapMaterial: string,
    dialColor: string,
    strapColor: string,
    housingThickness: string,
    strapLength: string,
    clockWork: string,
    waterResistance: string,
}
