export default {
  CREATE_ORDER_INIT: 'CREATE_ORDER_INIT',
  CREATE_ORDER_SUCCEED: 'CREATE_ORDER_SUCCEED',
  CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED',
  ADD__PRODUCT_TO_ORDER: 'ADD__PRODUCT_TO_ORDER',
};
